[package]
name = "ytmapi-rs"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.29.1", features = ["full"]}
reqwest = {version = "0.11.18", features = ["json"]}
serde = {version = "1.0.164", features = ["derive"]}
serde_json = "1.0.99"
sha1 = "0.10.5"
tokio-stream = "0.1.14"
async-stream = "0.3.5"
const_format = "0.2.31"
chrono = "0.4.31"
