[package]
name = "ytmapi-rs"
version = "0.0.2"
edition = "2021"
authors = ["nick42d"]
license = "MIT"
description = "An asynchronous (tokio) pure Rust API for Youtube Music using Google's internal API"
homepage = "https://github.com/nick42d/youtui"
repository = "https://github.com/nick42d/youtui"
readme = "README.md"

[dependencies]
tokio = {version = "1.29.1", features = ["full"]}
reqwest = {version = "0.12.1", features = ["json", "default"], default-features = false}
serde = {version = "1.0.164", features = ["derive"]}
serde_json = "1.0.99"
sha1 = "0.10.5"
tokio-stream = "0.1.14"
async-stream = "0.3.5"
const_format = "0.2.31"
chrono = "0.4.31"

[dev-dependencies]
pretty_assertions = "1"

[features]
default-tls = ["reqwest/default-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]
