# Using nightly for async traits
[toolchain]
channel = "nightly"

[package]
name = "youtui"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.5", features = ["derive"] }
crossterm = { version = "0.26.1", features = ["event-stream"] }
futures = "0.3.28"
ratatui = { version = "0.22.0", features = ["all-widgets"] }
serde = "1.0.164"
serde_json = "1.0.97"
tokio = "1.29.1"
ytmapi-rs = { path = "./ytmapi-rs" }
player = { git = "https://github.com/ccgauche/ytermusic", tag = "alpha-0.1.0" }
tracing = "0.1.37"
tui-logger = { version = "0.9.5", default-features = false, features = ["ratatui-support", "crossterm", "tracing-support"] }
tracing-subscriber = "0.3.17"
rustube = { version = "0.6.0", features = ["callback"] }
# Not the current version - this is required for Player
flume = "0.10.14"
anyhow = "1.0.75"
rusty_ytdl = { version = "0.6.3", features = ["tokio"] }
# it would be nice to use rodio but currently missing 
# rodio = { version = "0.17.1", features = ["symphonia-aac", "symphonia-isomp4"] }
