name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        toolchain: [nightly]


    steps:
    - uses: actions/checkout@v3
    
    - name: install linux deps
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libasound2-dev pkg-config
      if: contains(matrix.os, 'ubuntu')
      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: | 
        cargo test --verbose
        cargo test -p ytmapi-rs --verbose

